version: '3'
services:
  records:
    container_name: back-labka
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8100:8000
    volumes:
      - ./:/usr/src/app
